# Numpy

In [10]:
# imports and packages
import numpy as np

# 1D Array

In [11]:
my_array = [1,2,3]

In [12]:
type(my_array)

list

In [13]:
my_array= np.array([my_array])

In [14]:
np.shape(my_array)

(1, 3)

In [15]:
type(my_array)

numpy.ndarray

In [16]:
my_array = np.array([1,2,3])

In [17]:
np.shape(my_array)

(3,)

# 2D array

In [18]:
my_array = np.array ([
    [1,2,3],
    [4,5,6]
])

In [19]:
np.shape(my_array)

(2, 3)

In [20]:
my_array.T
#transposes the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
np.shape(my_array)

(2, 3)

In [22]:
trans_array = my_array.T

In [23]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [24]:
np.shape(trans_array)

(3, 2)

In [25]:
np.sum(trans_array, axis=0)
#adds Column

array([ 6, 15])

In [26]:
np.sum(trans_array, axis=1)
#adds rows

array([5, 7, 9])

# Measures of Central Tendency

In [27]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4, 9.5, 11,10.4,3,9.8], #jaguar
    [10.1, 11,9.1,20, 9.2,10.8,9.9,9.2,9.1,9.1, np.nan]#panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [28]:
#mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])