# Numpy

In [7]:
# imports and packages
import numpy as np
from scipy import stats
from statistics import multimode


In [8]:
%pip install numpy --upgrade
%pip install scipy -- upgrade
%pip install --upgrade pip

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


ERROR: Could not find a version that satisfies the requirement upgrade (from versions: none)
ERROR: No matching distribution found for upgrade


Note: you may need to restart the kernel to use updated packages.


# 1D Array

In [9]:
my_array = [1,2,3]

In [10]:
type(my_array)

list

In [11]:
my_array= np.array([my_array])

In [12]:
np.shape(my_array)

(1, 3)

In [13]:
type(my_array)

numpy.ndarray

In [14]:
my_array = np.array([1,2,3])

In [15]:
np.shape(my_array)

(3,)

# 2D array

In [16]:
my_array = np.array ([
    [1,2,3],
    [4,5,6]
])

In [17]:
np.shape(my_array)

(2, 3)

In [18]:
my_array.T
#transposes the array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [19]:
np.shape(my_array)

(2, 3)

In [20]:
trans_array = my_array.T

In [21]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
np.shape(trans_array)

(3, 2)

In [23]:
np.sum(trans_array, axis=0)
#adds Column

array([ 6, 15])

In [24]:
np.sum(trans_array, axis=1)
#adds rows

array([5, 7, 9])

# Measures of Central Tendency

In [25]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4, 9.5, 11,10.4,3,9.8],#jaguar
    [10.1, 11,9.1,20, 9.2,10.8,9.9,9.2,9.1,9.1, np.nan]#panther
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [26]:
np.shape(resistance)

(2, 11)

In [27]:
resistance.T

array([[10.6, 10.1],
       [ 9.1, 11. ],
       [ 9.3,  9.1],
       [ 9.8, 20. ],
       [10.5,  9.2],
       [10.4, 10.8],
       [ 9.5,  9.9],
       [11. ,  9.2],
       [10.4,  9.1],
       [ 3. ,  9.1],
       [ 9.8,  nan]])

In [28]:
np.mean(resistance,axis=0)
np.mean(resistance,axis=1)

array([9.4, nan])

In [29]:
#mean
np.nanmean(resistance, axis=1)

array([ 9.4 , 10.75])

In [31]:
jag_mean = np.nanmean(resistance,axis=1)[0]
pan_mean = np.nanmean(resistance,axis=1)[1]

print(f'Jaguar_mean = {jag_mean:.2f} ohms')
print(f'Panther_mean = {pan_mean:.2f} ohms')

Jaguar_mean = 9.40 ohms
Panther_mean = 10.75 ohms


In [32]:
#Median
np.nanmedian(resistance,axis=1)

array([9.8 , 9.55])

In [33]:
jag_median = np.nanmedian(resistance,axis=1)[0]
pan_median = np.nanmedian(resistance,axis=1)[1]

print(f'Jaguar_median = {jag_median:.2f} ohms')
print(f'Panther_median = {pan_median:.2f} ohms')

Jaguar_median = 9.80 ohms
Panther_median = 9.55 ohms


In [34]:
# Mode
stats.mode(resistance,axis=1)

ModeResult(mode=array([9.8, 9.1]), count=array([2, 3]))

In [36]:
my_array = [1,1,2,2,3,4,5]
multimode(my_array)

[1, 2]

In [37]:
jag_res = resistance[0]

print("Jaguar mode: ")
for i in multimode(jag_res):
    print(f'{i} ohms')

Jaguar mode: 
9.8 ohms
10.4 ohms


In [38]:
pan_res = resistance[0]

print("Panther mode: ")
for i in multimode(pan_res):
    print(f'{i} ohms')

Panther mode: 
9.8 ohms
10.4 ohms


# Measures of Variability

In [40]:
#Jaguar vs Panther
resistance = np.array([
    [10.6, 9.1, 9.3, 9.8, 10.5, 10.4, 9.5, 11, 10.4, 3, 9.8],
    [10.1, 11, 9.1, 20, 9.2, 10.8, 9.9, 9.2, 9.1, 9.1, np.nan]
])
resistance

array([[10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8],
       [10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1,  nan]])

In [41]:
#Range
res_max = np.nanmax(resistance,axis=1)
res_min = np.nanmin(resistance,axis=1)

res_range = res_max - res_min
res_range

array([ 8. , 10.9])

In [42]:
print(f'Jaguar_range = {res_range[0]:.2f} ohms')
print(f'Panther_range = {res_range[1]:.2f} ohms')

Jaguar_range = 8.00 ohms
Panther_range = 10.90 ohms


In [43]:
#1st Quartile
res_Q1 = np.nanpercentile(resistance,25,axis=1)
res_Q1

array([9.4  , 9.125])

In [44]:
#2nd Quartile
res_Q2 = np.nanpercentile(resistance,50,axis=1)
res_Q2

array([9.8 , 9.55])

In [45]:
#3rd Quartile
res_Q3 = np.nanpercentile(resistance,75,axis=1)
res_Q3

array([10.45 , 10.625])

In [46]:
# IQR
print(f'Jaguar IQR = {res_Q3[0] - res_Q1[0]:.2f} ohms')
print(f'Panther IQR = {res_Q3[1] - res_Q1[1]:.2f} ohms')

Jaguar IQR = 1.05 ohms
Panther IQR = 1.50 ohms


In [47]:
# Variance
res_var = np.nanvar(resistance,ddof=1,axis=1)
res_var

array([ 4.86      , 11.08277778])

In [48]:
print(f'Jaguar Variance = {res_var[0]:.2f} ohms')
print(f'Panther Variance = {res_var[1]:.2f} ohms')

Jaguar Variance = 4.86 ohms
Panther Variance = 11.08 ohms


In [49]:
#Standard Deviation
res_std = np.nanstd(resistance,ddof=1,axis=1)
res_std

array([2.20454077, 3.32908062])

In [50]:
print(f'Jaguar Standard Deviation = {res_std[0]:.2f} ohms')
print(f'Panther Standard Deviation = {res_std[1]:.2f} ohms')

Jaguar Standard Deviation = 2.20 ohms
Panther Standard Deviation = 3.33 ohms
